name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-version: ['4.09.0', '4.08.1']
    steps:
      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - uses: actions/checkout@v2

      - name: Pin package
        run: opam pin add tyxml-components.dev -n .

      - name: Query and install external dependencies
        run: opam depext -yt tyxml-components

      - name: Install dependencies
        run: make dev

      - name: Build
        run: make build

      - name: Check formatting
        run: make format

      - name: Run tests
        run: make test
